#include <iostream>
#include "symbol_table/symbol_table.hpp" // Include if your main interacts with SymbolTable

// Declare external functions generated by Flex/Bison
extern int yyparse();
extern void yyerror(const char *s);

/*int main() {
    // Initialize your symbol table's global scope
    SymbolTable::enter_scope();

    std::cout << "Starting syntax analysis...\n";
    int result = yyparse(); // Call the Bison parser

    // Print symbol table contents (for debugging)
    SymbolTable::print_all();

    // Exit the global scope
    SymbolTable::exit_scope();

    if (result == 0) {
        std::cout << "Analysis completed successfully!\n";
    } else {
        std::cout << "Analysis completed with errors.\n";
    }

    return result;
}*/