#include <iostream>
#include "symbol_table/symbol_table.hpp" // Include if your main interacts with SymbolTable

// Declare external functions generated by Flex/Bison
extern int yyparse();
extern void yyerror(const char *s);
